version: '3'

services:
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
      - POSTGRES_DB=fastapi
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "8888:80"
    restart: unless-stopped
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge

volumes:
    postgres:
    pgadmin: